export const VehicleColors = [
    {
        id: "0",
        name: "Metallic Black",
        cssColorString: "#0d1116",
        rgbColorString: "13, 17, 22",
    },
    {
        id: "1",
        name: "Metallic Graphite Black",
        cssColorString: "#1c1d21",
        rgbColorString: "28, 29, 33",
    },
    {
        id: "2",
        name: "Metallic Black Steal",
        cssColorString: "#32383d",
        rgbColorString: "50, 56, 61",
    },
    {
        id: "3",
        name: "Metallic Dark Silver",
        cssColorString: "#454b4f",
        rgbColorString: "69, 75, 79",
    },
    {
        id: "4",
        name: "Metallic Silver",
        cssColorString: "#999da0",
        rgbColorString: "153, 157, 160",
    },
    {
        id: "5",
        name: "Metallic Blue Silver",
        cssColorString: "#c2c4c6",
        rgbColorString: "194, 196, 198",
    },
    {
        id: "6",
        name: "Metallic Steel Gray",
        cssColorString: "#979a97",
        rgbColorString: "151, 154, 151",
    },
    {
        id: "7",
        name: "Metallic Shadow Silver",
        cssColorString: "#637380",
        rgbColorString: "99, 115, 128",
    },
    {
        id: "8",
        name: "Metallic Stone Silver",
        cssColorString: "#63625c",
        rgbColorString: "99, 98, 92",
    },
    {
        id: "9",
        name: "Metallic Midnight Silver",
        cssColorString: "#3c3f47",
        rgbColorString: "60, 63, 71",
    },
    {
        id: "10",
        name: "Metallic Gun Metal",
        cssColorString: "#444e54",
        rgbColorString: "68, 78, 84",
    },
    {
        id: "11",
        name: "Metallic Anthracite Grey",
        cssColorString: "#1d2129",
        rgbColorString: "29, 33, 41",
    },
    {
        id: "12",
        name: "Matte Black",
        cssColorString: "#13181f",
        rgbColorString: "19, 24, 31",
    },
    {
        id: "13",
        name: "Matte Gray",
        cssColorString: "#26282a",
        rgbColorString: "38, 40, 42",
    },
    {
        id: "14",
        name: "Matte Light Grey",
        cssColorString: "#515554",
        rgbColorString: "81, 85, 84",
    },
    {
        id: "15",
        name: "Util Black",
        cssColorString: "#151921",
        rgbColorString: "21, 25, 33",
    },
    {
        id: "16",
        name: "Util Black Poly",
        cssColorString: "#1e2429",
        rgbColorString: "30, 36, 41",
    },
    {
        id: "17",
        name: "Util Dark silver",
        cssColorString: "#333a3c",
        rgbColorString: "51, 58, 60",
    },
    {
        id: "18",
        name: "Util Silver",
        cssColorString: "#8c9095",
        rgbColorString: "140, 144, 149",
    },
    {
        id: "19",
        name: "Util Gun Metal",
        cssColorString: "#39434d",
        rgbColorString: "57, 67, 77",
    },
    {
        id: "20",
        name: "Util Shadow Silver",
        cssColorString: "#506272",
        rgbColorString: "80, 98, 114",
    },
    {
        id: "21",
        name: "Worn Black",
        cssColorString: "#1e232f",
        rgbColorString: "30, 35, 47",
    },
    {
        id: "22",
        name: "Worn Graphite",
        cssColorString: "#363a3f",
        rgbColorString: "54, 58, 63",
    },
    {
        id: "23",
        name: "Worn Silver Grey",
        cssColorString: "#a0a199",
        rgbColorString: "160, 161, 153",
    },
    {
        id: "24",
        name: "Worn Silver",
        cssColorString: "#d3d3d3",
        rgbColorString: "211, 211, 211",
    },
    {
        id: "25",
        name: "Worn Blue Silver",
        cssColorString: "#b7bfca",
        rgbColorString: "183, 191, 202",
    },
    {
        id: "26",
        name: "Worn Shadow Silver",
        cssColorString: "#778794",
        rgbColorString: "119, 135, 148",
    },
    {
        id: "27",
        name: "Metallic Red",
        cssColorString: "#c00e1a",
        rgbColorString: "192, 14, 26",
    },
    {
        id: "28",
        name: "Metallic Torino Red",
        cssColorString: "#da1918",
        rgbColorString: "218, 25, 24",
    },
    {
        id: "29",
        name: "Metallic Formula Red",
        cssColorString: "#b6111b",
        rgbColorString: "182, 17, 27",
    },
    {
        id: "30",
        name: "Metallic Blaze Red",
        cssColorString: "#a51e23",
        rgbColorString: "165, 30, 35",
    },
    {
        id: "31",
        name: "Metallic Graceful Red",
        cssColorString: "#7b1a22",
        rgbColorString: "123, 26, 34",
    },
    {
        id: "32",
        name: "Metallic Garnet Red",
        cssColorString: "#8e1b1f",
        rgbColorString: "142, 27, 31",
    },
    {
        id: "33",
        name: "Metallic Desert Red",
        cssColorString: "#6f1818",
        rgbColorString: "111, 24, 24",
    },
    {
        id: "34",
        name: "Metallic Cabernet Red",
        cssColorString: "#49111d",
        rgbColorString: "73, 17, 29",
    },
    {
        id: "35",
        name: "Metallic Candy Red",
        cssColorString: "#b60f25",
        rgbColorString: "182, 15, 37",
    },
    {
        id: "36",
        name: "Metallic Sunrise Orange",
        cssColorString: "#d44a17",
        rgbColorString: "212, 74, 23",
    },
    {
        id: "37",
        name: "Metallic Classic Gold",
        cssColorString: "#c2944f",
        rgbColorString: "194, 148, 79",
    },
    {
        id: "38",
        name: "Metallic Orange",
        cssColorString: "#f78616",
        rgbColorString: "247, 134, 22",
    },
    {
        id: "39",
        name: "Matte Red",
        cssColorString: "#cf1f21",
        rgbColorString: "207, 31, 33",
    },
    {
        id: "40",
        name: "Matte Dark Red",
        cssColorString: "#732021",
        rgbColorString: "115, 32, 33",
    },
    {
        id: "41",
        name: "Matte Orange",
        cssColorString: "#f27d20",
        rgbColorString: "242, 125, 32",
    },
    {
        id: "42",
        name: "Matte Yellow",
        cssColorString: "#ffc91f",
        rgbColorString: "255, 201, 31",
    },
    {
        id: "43",
        name: "Util Red",
        cssColorString: "#9c1016",
        rgbColorString: "156, 16, 22",
    },
    {
        id: "44",
        name: "Util Bright Red",
        cssColorString: "#de0f18",
        rgbColorString: "222, 15, 24",
    },
    {
        id: "45",
        name: "Util Garnet Red",
        cssColorString: "#8f1e17",
        rgbColorString: "143, 30, 23",
    },
    {
        id: "46",
        name: "Worn Red",
        cssColorString: "#a94744",
        rgbColorString: "169, 71, 68",
    },
    {
        id: "47",
        name: "Worn Golden Red",
        cssColorString: "#b16c51",
        rgbColorString: "177, 108, 81",
    },
    {
        id: "48",
        name: "Worn Dark Red",
        cssColorString: "#371c25",
        rgbColorString: "55, 28, 37",
    },
    {
        id: "49",
        name: "Metallic Dark Green",
        cssColorString: "#132428",
        rgbColorString: "19, 36, 40",
    },
    {
        id: "50",
        name: "Metallic Racing Green",
        cssColorString: "#122e2b",
        rgbColorString: "18, 46, 43",
    },
    {
        id: "51",
        name: "Metallic Sea Green",
        cssColorString: "#12383c",
        rgbColorString: "18, 56, 60",
    },
    {
        id: "52",
        name: "Metallic Olive Green",
        cssColorString: "#31423f",
        rgbColorString: "49, 66, 63",
    },
    {
        id: "53",
        name: "Metallic Green",
        cssColorString: "#155c2d",
        rgbColorString: "21, 92, 45",
    },
    {
        id: "54",
        name: "Metallic Gasoline Blue Green",
        cssColorString: "#1b6770",
        rgbColorString: "27, 103, 112",
    },
    {
        id: "55",
        name: "Matte Lime Green",
        cssColorString: "#66b81f",
        rgbColorString: "102, 184, 31",
    },
    {
        id: "56",
        name: "Util Dark Green",
        cssColorString: "#22383e",
        rgbColorString: "34, 56, 62",
    },
    {
        id: "57",
        name: "Util Green",
        cssColorString: "#1d5a3f",
        rgbColorString: "29, 90, 63",
    },
    {
        id: "58",
        name: "Worn Dark Green",
        cssColorString: "#2d423f",
        rgbColorString: "45, 66, 63",
    },
    {
        id: "59",
        name: "Worn Green",
        cssColorString: "#45594b",
        rgbColorString: "69, 89, 75",
    },
    {
        id: "60",
        name: "Worn Sea Wash",
        cssColorString: "#65867f",
        rgbColorString: "101, 134, 127",
    },
    {
        id: "61",
        name: "Metallic Midnight Blue",
        cssColorString: "#222e46",
        rgbColorString: "34, 46, 70",
    },
    {
        id: "62",
        name: "Metallic Dark Blue",
        cssColorString: "#233155",
        rgbColorString: "35, 49, 85",
    },
    {
        id: "63",
        name: "Metallic Saxony Blue",
        cssColorString: "#304c7e",
        rgbColorString: "48, 76, 126",
    },
    {
        id: "64",
        name: "Metallic Blue",
        cssColorString: "#47578f",
        rgbColorString: "71, 87, 143",
    },
    {
        id: "65",
        name: "Metallic Mariner Blue",
        cssColorString: "#637ba7",
        rgbColorString: "99, 123, 167",
    },
    {
        id: "66",
        name: "Metallic Harbor Blue",
        cssColorString: "#394762",
        rgbColorString: "57, 71, 98",
    },
    {
        id: "67",
        name: "Metallic Diamond Blue",
        cssColorString: "#d6e7f1",
        rgbColorString: "214, 231, 241",
    },
    {
        id: "68",
        name: "Metallic Surf Blue",
        cssColorString: "#76afbe",
        rgbColorString: "118, 175, 190",
    },
    {
        id: "69",
        name: "Metallic Nautical Blue",
        cssColorString: "#345e72",
        rgbColorString: "52, 94, 114",
    },
    {
        id: "70",
        name: "Metallic Bright Blue",
        cssColorString: "#0b9cf1",
        rgbColorString: "11, 156, 241",
    },
    {
        id: "71",
        name: "Metallic Purple Blue",
        cssColorString: "#2f2d52",
        rgbColorString: "47, 45, 82",
    },
    {
        id: "72",
        name: "Metallic Spinnaker Blue",
        cssColorString: "#282c4d",
        rgbColorString: "40, 44, 77",
    },
    {
        id: "73",
        name: "Metallic Ultra Blue",
        cssColorString: "#2354a1",
        rgbColorString: "35, 84, 161",
    },
    {
        id: "74",
        name: "Metallic Bright Blue",
        cssColorString: "#6ea3c6",
        rgbColorString: "110, 163, 198",
    },
    {
        id: "75",
        name: "Util Dark Blue",
        cssColorString: "#112552",
        rgbColorString: "17, 37, 82",
    },
    {
        id: "76",
        name: "Util Midnight Blue",
        cssColorString: "#1b203e",
        rgbColorString: "27, 32, 62",
    },
    {
        id: "77",
        name: "Util Blue",
        cssColorString: "#275190",
        rgbColorString: "39, 81, 144",
    },
    {
        id: "78",
        name: "Util Sea Foam Blue",
        cssColorString: "#608592",
        rgbColorString: "96, 133, 146",
    },
    {
        id: "79",
        name: "Util Lightning blue",
        cssColorString: "#2446a8",
        rgbColorString: "36, 70, 168",
    },
    {
        id: "80",
        name: "Util Maui Blue Poly",
        cssColorString: "#4271e1",
        rgbColorString: "66, 113, 225",
    },
    {
        id: "81",
        name: "Util Bright Blue",
        cssColorString: "#3b39e0",
        rgbColorString: "59, 57, 224",
    },
    {
        id: "82",
        name: "Matte Dark Blue",
        cssColorString: "#1f2852",
        rgbColorString: "31, 40, 82",
    },
    {
        id: "83",
        name: "Matte Blue",
        cssColorString: "#253aa7",
        rgbColorString: "37, 58, 167",
    },
    {
        id: "84",
        name: "Matte Midnight Blue",
        cssColorString: "#1c3551",
        rgbColorString: "28, 53, 81",
    },
    {
        id: "85",
        name: "Worn Dark blue",
        cssColorString: "#4c5f81",
        rgbColorString: "76, 95, 129",
    },
    {
        id: "86",
        name: "Worn Blue",
        cssColorString: "#58688e",
        rgbColorString: "88, 104, 142",
    },
    {
        id: "87",
        name: "Worn Light blue",
        cssColorString: "#74b5d8",
        rgbColorString: "116, 181, 216",
    },
    {
        id: "88",
        name: "Metallic Taxi Yellow",
        cssColorString: "#ffcf20",
        rgbColorString: "255, 207, 32",
    },
    {
        id: "89",
        name: "Metallic Race Yellow",
        cssColorString: "#fbe212",
        rgbColorString: "251, 226, 18",
    },
    {
        id: "90",
        name: "Metallic Bronze",
        cssColorString: "#916532",
        rgbColorString: "145, 101, 50",
    },
    {
        id: "91",
        name: "Metallic Yellow Bird",
        cssColorString: "#e0e13d",
        rgbColorString: "224, 225, 61",
    },
    {
        id: "92",
        name: "Metallic Lime",
        cssColorString: "#98d223",
        rgbColorString: "152, 210, 35",
    },
    {
        id: "93",
        name: "Metallic Champagne",
        cssColorString: "#9b8c78",
        rgbColorString: "155, 140, 120",
    },
    {
        id: "94",
        name: "Metallic Pueblo Beige",
        cssColorString: "#503218",
        rgbColorString: "80, 50, 24",
    },
    {
        id: "95",
        name: "Metallic Dark Ivory",
        cssColorString: "#473f2b",
        rgbColorString: "71, 63, 43",
    },
    {
        id: "96",
        name: "Metallic Choco Brown",
        cssColorString: "#221b19",
        rgbColorString: "34, 27, 25",
    },
    {
        id: "97",
        name: "Metallic Golden Brown",
        cssColorString: "#653f23",
        rgbColorString: "101, 63, 35",
    },
    {
        id: "98",
        name: "Metallic Light Brown",
        cssColorString: "#775c3e",
        rgbColorString: "119, 92, 62",
    },
    {
        id: "99",
        name: "Metallic Straw Beige",
        cssColorString: "#ac9975",
        rgbColorString: "172, 153, 117",
    },
    {
        id: "100",
        name: "Metallic Moss Brown",
        cssColorString: "#6c6b4b",
        rgbColorString: "108, 107, 75",
    },
    {
        id: "101",
        name: "Metallic Biston Brown",
        cssColorString: "#402e2b",
        rgbColorString: "64, 46, 43",
    },
    {
        id: "102",
        name: "Metallic Beechwood",
        cssColorString: "#a4965f",
        rgbColorString: "164, 150, 95",
    },
    {
        id: "103",
        name: "Metallic Dark Beechwood",
        cssColorString: "#46231a",
        rgbColorString: "70, 35, 26",
    },
    {
        id: "104",
        name: "Metallic Choco Orange",
        cssColorString: "#752b19",
        rgbColorString: "117, 43, 25",
    },
    {
        id: "105",
        name: "Metallic Beach Sand",
        cssColorString: "#bfae7b",
        rgbColorString: "191, 174, 123",
    },
    {
        id: "106",
        name: "Metallic Sun Bleeched Sand",
        cssColorString: "#dfd5b2",
        rgbColorString: "223, 213, 178",
    },
    {
        id: "107",
        name: "Metallic Cream",
        cssColorString: "#f7edd5",
        rgbColorString: "247, 237, 213",
    },
    {
        id: "108",
        name: "Util Brown",
        cssColorString: "#3a2a1b",
        rgbColorString: "58, 42, 27",
    },
    {
        id: "109",
        name: "Util Medium Brown",
        cssColorString: "#785f33",
        rgbColorString: "120, 95, 51",
    },
    {
        id: "110",
        name: "Util Light Brown",
        cssColorString: "#b5a079",
        rgbColorString: "181, 160, 121",
    },
    {
        id: "111",
        name: "Metallic White",
        cssColorString: "#fffff6",
        rgbColorString: "255, 255, 246",
    },
    {
        id: "112",
        name: "Metallic Frost White",
        cssColorString: "#eaeaea",
        rgbColorString: "234, 234, 234",
    },
    {
        id: "113",
        name: "Worn Honey Beige",
        cssColorString: "#b0ab94",
        rgbColorString: "176, 171, 148",
    },
    {
        id: "114",
        name: "Worn Brown",
        cssColorString: "#453831",
        rgbColorString: "69, 56, 49",
    },
    {
        id: "115",
        name: "Worn Dark Brown",
        cssColorString: "#2a282b",
        rgbColorString: "42, 40, 43",
    },
    {
        id: "116",
        name: "Worn straw beige",
        cssColorString: "#726c57",
        rgbColorString: "114, 108, 87",
    },
    {
        id: "117",
        name: "Brushed Steel",
        cssColorString: "#6a747c",
        rgbColorString: "106, 116, 124",
    },
    {
        id: "118",
        name: "Brushed Black steel",
        cssColorString: "#354158",
        rgbColorString: "53, 65, 88",
    },
    {
        id: "119",
        name: "Brushed Aluminium",
        cssColorString: "#9ba0a8",
        rgbColorString: "155, 160, 168",
    },
    {
        id: "120",
        name: "Chrome",
        cssColorString: "#5870a1",
        rgbColorString: "88, 112, 161",
    },
    {
        id: "121",
        name: "Worn Off White",
        cssColorString: "#eae6de",
        rgbColorString: "234, 230, 222",
    },
    {
        id: "122",
        name: "Util Off White",
        cssColorString: "#dfddd0",
        rgbColorString: "223, 221, 208",
    },
    {
        id: "123",
        name: "Worn Orange",
        cssColorString: "#f2ad2e",
        rgbColorString: "242, 173, 46",
    },
    {
        id: "124",
        name: "Worn Light Orange",
        cssColorString: "#f9a458",
        rgbColorString: "249, 164, 88",
    },
    {
        id: "125",
        name: "Metallic Securicor Green",
        cssColorString: "#83c566",
        rgbColorString: "131, 197, 102",
    },
    {
        id: "126",
        name: "Worn Taxi Yellow",
        cssColorString: "#f1cc40",
        rgbColorString: "241, 204, 64",
    },
    {
        id: "127",
        name: "police car blue",
        cssColorString: "#4cc3da",
        rgbColorString: "76, 195, 218",
    },
    {
        id: "128",
        name: "Matte Green",
        cssColorString: "#4e6443",
        rgbColorString: "78, 100, 67",
    },
    {
        id: "129",
        name: "Matte Brown",
        cssColorString: "#bcac8f",
        rgbColorString: "188, 172, 143",
    },
    {
        id: "130",
        name: "Worn Orange",
        cssColorString: "#f8b658",
        rgbColorString: "248, 182, 88",
    },
    {
        id: "131",
        name: "Matte White",
        cssColorString: "#fcf9f1",
        rgbColorString: "252, 249, 241",
    },
    {
        id: "132",
        name: "Worn White",
        cssColorString: "#fffffb",
        rgbColorString: "255, 255, 251",
    },
    {
        id: "133",
        name: "Worn Olive Army Green",
        cssColorString: "#81844c",
        rgbColorString: "129, 132, 76",
    },
    {
        id: "134",
        name: "Pure White",
        cssColorString: "#ffffff",
        rgbColorString: "255, 255, 255",
    },
    {
        id: "135",
        name: "Hot Pink",
        cssColorString: "#f21f99",
        rgbColorString: "242, 31, 153",
    },
    {
        id: "136",
        name: "Salmon pink",
        cssColorString: "#fdd6cd",
        rgbColorString: "253, 214, 205",
    },
    {
        id: "137",
        name: "Metallic Vermillion Pink",
        cssColorString: "#df5891",
        rgbColorString: "223, 88, 145",
    },
    {
        id: "138",
        name: "Orange",
        cssColorString: "#f6ae20",
        rgbColorString: "246, 174, 32",
    },
    {
        id: "139",
        name: "Green",
        cssColorString: "#b0ee6e",
        rgbColorString: "176, 238, 110",
    },
    {
        id: "140",
        name: "Blue",
        cssColorString: "#08e9fa",
        rgbColorString: "8, 233, 250",
    },
    {
        id: "141",
        name: "Mettalic Black Blue",
        cssColorString: "#0a0c17",
        rgbColorString: "10, 12, 23",
    },
    {
        id: "142",
        name: "Metallic Black Purple",
        cssColorString: "#0c0d18",
        rgbColorString: "12, 13, 24",
    },
    {
        id: "143",
        name: "Metallic Black Red",
        cssColorString: "#0e0d14",
        rgbColorString: "14, 13, 20",
    },
    {
        id: "144",
        name: "hunter green",
        cssColorString: "#9f9e8a",
        rgbColorString: "159, 158, 138",
    },
    {
        id: "145",
        name: "Metallic Purple",
        cssColorString: "#621276",
        rgbColorString: "98, 18, 118",
    },
    {
        id: "146",
        name: "Metaillic V Dark Blue",
        cssColorString: "#0b1421",
        rgbColorString: "11, 20, 33",
    },
    {
        id: "147",
        name: "MODSHOP BLACK1",
        cssColorString: "#11141a",
        rgbColorString: "17, 20, 26",
    },
    {
        id: "148",
        name: "Matte Purple",
        cssColorString: "#6b1f7b",
        rgbColorString: "107, 31, 123",
    },
    {
        id: "149",
        name: "Matte Dark Purple",
        cssColorString: "#1e1d22",
        rgbColorString: "30, 29, 34",
    },
    {
        id: "150",
        name: "Metallic Lava Red",
        cssColorString: "#bc1917",
        rgbColorString: "188, 25, 23",
    },
    {
        id: "151",
        name: "Matte Forest Green",
        cssColorString: "#2d362a",
        rgbColorString: "45, 54, 42",
    },
    {
        id: "152",
        name: "Matte Olive Drab",
        cssColorString: "#696748",
        rgbColorString: "105, 103, 72",
    },
    {
        id: "153",
        name: "Matte Desert Brown",
        cssColorString: "#7a6c55",
        rgbColorString: "122, 108, 85",
    },
    {
        id: "154",
        name: "Matte Desert Tan",
        cssColorString: "#c3b492",
        rgbColorString: "195, 180, 146",
    },
    {
        id: "155",
        name: "Matte Foilage Green",
        cssColorString: "#5a6352",
        rgbColorString: "90, 99, 82",
    },
    {
        id: "156",
        name: "DEFAULT ALLOY COLOR",
        cssColorString: "#81827f",
        rgbColorString: "129, 130, 127",
    },
    {
        id: "157",
        name: "Epsilon Blue",
        cssColorString: "#afd6e4",
        rgbColorString: "175, 214, 228",
    },
    {
        id: "158",
        name: "Pure Gold",
        cssColorString: "#7a6440",
        rgbColorString: "122, 100, 64",
    },
    {
        id: "159",
        name: "Brushed Gold",
        cssColorString: "#7f6a48",
        rgbColorString: "127, 106, 72",
    }
]
